---
deployment:
  tasks:
    - export DEPLOYPATH=/home/milkwoodadmin/public_html/ntirhisano.cc
    - npm install
    - npm run build
    - rm -rf "$DEPLOYPATH"/*
    - mkdir -p "$DEPLOYPATH"
    - cp -R public/* "$DEPLOYPATH"